// Generated by gencpp from file topicImgThreadcpp/BoundingBox.msg
// DO NOT EDIT!


#ifndef TOPICIMGTHREADCPP_MESSAGE_BOUNDINGBOX_H
#define TOPICIMGTHREADCPP_MESSAGE_BOUNDINGBOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace topicImgThreadcpp
{
template <class ContainerAllocator>
struct BoundingBox_
{
  typedef BoundingBox_<ContainerAllocator> Type;

  BoundingBox_()
    : Class(0)
    , probability(0.0)
    , xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)  {
    }
  BoundingBox_(const ContainerAllocator& _alloc)
    : Class(0)
    , probability(0.0)
    , xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)  {
  (void)_alloc;
    }



   typedef int64_t _Class_type;
  _Class_type Class;

   typedef double _probability_type;
  _probability_type probability;

   typedef int64_t _xmin_type;
  _xmin_type xmin;

   typedef int64_t _ymin_type;
  _ymin_type ymin;

   typedef int64_t _xmax_type;
  _xmax_type xmax;

   typedef int64_t _ymax_type;
  _ymax_type ymax;





  typedef boost::shared_ptr< ::topicImgThreadcpp::BoundingBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::topicImgThreadcpp::BoundingBox_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox_

typedef ::topicImgThreadcpp::BoundingBox_<std::allocator<void> > BoundingBox;

typedef boost::shared_ptr< ::topicImgThreadcpp::BoundingBox > BoundingBoxPtr;
typedef boost::shared_ptr< ::topicImgThreadcpp::BoundingBox const> BoundingBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::topicImgThreadcpp::BoundingBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::topicImgThreadcpp::BoundingBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace topicImgThreadcpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'topicImgThreadcpp': ['/home/ac-optimus/video/darknet_ros_ntwoc/src/topicImgThreadcpp/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::topicImgThreadcpp::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topicImgThreadcpp::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topicImgThreadcpp::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topicImgThreadcpp::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topicImgThreadcpp::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topicImgThreadcpp::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::topicImgThreadcpp::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25b0e0110aaf9232e8c23d5affb594dc";
  }

  static const char* value(const ::topicImgThreadcpp::BoundingBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25b0e0110aaf9232ULL;
  static const uint64_t static_value2 = 0xe8c23d5affb594dcULL;
};

template<class ContainerAllocator>
struct DataType< ::topicImgThreadcpp::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "topicImgThreadcpp/BoundingBox";
  }

  static const char* value(const ::topicImgThreadcpp::BoundingBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::topicImgThreadcpp::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 Class\n\
float64 probability\n\
int64 xmin\n\
int64 ymin\n\
int64 xmax\n\
int64 ymax\n\
";
  }

  static const char* value(const ::topicImgThreadcpp::BoundingBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::topicImgThreadcpp::BoundingBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Class);
      stream.next(m.probability);
      stream.next(m.xmin);
      stream.next(m.ymin);
      stream.next(m.xmax);
      stream.next(m.ymax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::topicImgThreadcpp::BoundingBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::topicImgThreadcpp::BoundingBox_<ContainerAllocator>& v)
  {
    s << indent << "Class: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Class);
    s << indent << "probability: ";
    Printer<double>::stream(s, indent + "  ", v.probability);
    s << indent << "xmin: ";
    Printer<int64_t>::stream(s, indent + "  ", v.xmin);
    s << indent << "ymin: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ymin);
    s << indent << "xmax: ";
    Printer<int64_t>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymax: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ymax);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOPICIMGTHREADCPP_MESSAGE_BOUNDINGBOX_H
